#!/bin/bash

cmake ~/Documents/Raspoznavaika/raspoznavayka/src/ ~/Documents/Raspoznavaika/raspoznavayka/build/
cd ~/Documents/Raspoznavaika/raspoznavayka/build/
make

cd ..
~/Documents/Raspoznavaika/raspoznavayka/build/raspoznavayka
